server:
  port: 8080
  servlet:
    session:
      timeout: 30s

modbus:
  host: 192.168.3.1
  port: 502
  slave_id: 1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plc
    username: root
    password: 12345678
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      idle-timeout: 300000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      password: Hangzhou@123
      host: 127.0.0.1
      database: 0

jasypt:
  encryptor:
    password: +K2U9T6yDqPvzKV+hF+

config:
  password: ENC(P5vSfE7HbeF+1inAbpNxu2I1D/rCscgsyuXMYgf1E4c7Ilt88VsrwLTWpPfdFJQU)

logging:
  file:
    path: ./log
