server:
  port: 8080

modbus:
  host: 192.168.3.1
  port: 502
  slave_id: 1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plc
    username: root
    password: 12345678
    hikari:
      minimum-idle: 1
      idle-timeout: 300000
      maximum-pool-size: 10
      driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    url: jdbc:mysql://localhost:3306/plc
    user: root
    password: 12345678
    create-schemas: on
    schemas: migration
    driver-class-name: com.mysql.cj.jdbc.Driver

jasypt:
  encryptor:
    password: +K2U9T6yDqPvzKV+hF+

config:
  password: ENC(P5vSfE7HbeF+1inAbpNxu2I1D/rCscgsyuXMYgf1E4c7Ilt88VsrwLTWpPfdFJQU)

logging:
  file:
    path: ./log